[build]
builder = "NIXPACKS"

[build.nixpacksPlan]
providers = ["python"]

[build.nixpacksPlan.phases.setup]
nixPkgs = ["python311", "chromium", "chromium-driver", "python3-pip"]

[deploy]
startCommand = "gunicorn app:app --bind 0.0.0.0:8080"

[phases.setup]
packages = ["chromium", "chromium-driver", "python3", "python3-pip"]


